dofile("weapons_and_combat/bombdef/splatbomb.lua")
dofile("weapons_and_combat/bombdef/burstbomb.lua")
dofile("weapons_and_combat/bombdef/suctionbomb.lua")
--dofile("weapons/bombdef/zipcaster.lua")
dofile("weapons_and_combat/bombdef/sprinkler.lua")
