dofile("weapons_and_combat/def/basic.lua")
dofile("weapons_and_combat/def/aerospray.lua")
dofile("weapons_and_combat/def/charger.lua")
dofile("weapons_and_combat/def/blaster.lua")
dofile("weapons_and_combat/def/dualie_squelchers.lua")
dofile("weapons_and_combat/def/splat_dualies.lua")
dofile("weapons_and_combat/def/brella.lua")
dofile("weapons_and_combat/def/undercover_brella.lua")
dofile("weapons_and_combat/def/splatana_wiper.lua")
dofile("weapons_and_combat/def/52gal.lua")

dofile("weapons_and_combat/def/ZE2/accelring.lua")
dofile("weapons_and_combat/def/ZE2/fist.lua")

dofile("weapons_and_combat/def/special/rainmaker.lua")
